require 'rake/clean'

CLEAN.include( '*.gch', '*.o' )
CLOBBER.include( 'face_detection' )

OPENCV_UTILS = '../../opencv_utils'

CC = 'gcc'
CFLAGS = `pkg-config --cflags opencv`.chomp + "-I#{OPENCV_UTILS}"
LFLAGS = `pkg-config --libs opencv`.chomp

OBJECTS = ['face_detection.o', 'image_raii.o', 'histogram_raii.o', 'window_raii.o']

task :default => ["face_detection"]

task :run do
  system( "./face_detection Friends.jpg" )
end

file "face_detection" => OBJECTS do
  sh "#{CC} -o face_detection #{OBJECTS.join( ' ' )} #{LFLAGS}"
end

file "face_detection.o" => ['face_detection.cpp', "#{OPENCV_UTILS}/image_raii.cpp"] do
  sh "#{CC} -c face_detection.cpp #{CFLAGS}"
end

file "image_raii.o" => ["#{OPENCV_UTILS}/image_raii.cpp", "#{OPENCV_UTILS}/image_raii.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/image_raii.cpp #{CFLAGS}"
end

file "histogram_raii.o" => ["#{OPENCV_UTILS}/histogram_raii.cpp", "#{OPENCV_UTILS}/histogram_raii.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/histogram_raii.cpp #{CFLAGS}"
end

file "window_raii.o" => ["#{OPENCV_UTILS}/window_raii.cpp", "#{OPENCV_UTILS}/window_raii.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/window_raii.cpp #{CFLAGS}"
end
