RUBY_BIN = "jruby"
INBOX_PATH = "/home/hone/.evolution/mail/imap/hone@mail.hone.wornpath.net/folders/INBOX"
SENT_PATH = "/home/hone/.evolution/mail/imap/hone@mail.hone.wornpath.net/folders/INBOX/subfolders/Sent"
OLD_MESSAGES_PATH = "/home/hone/.evolution/mail/imap/hone@mail.hone.wornpath.net/folders/INBOX/subfolders/old-messages"
SERIALIZED_FILE = "mail.dump"
RUN_FILE = "runner.rb"
THREADS = 2

desc "load files inbox"
task :load_inbox do
  sh "#{RUBY_BIN} #{RUN_FILE} #{SERIALIZED_FILE} #{THREADS} #{INBOX_PATH}"
end

desc "load files sent"
task :load_sent do
  sh "#{RUBY_BIN} #{RUN_FILE} #{SERIALIZED_FILE} #{THREADS} #{SENT_PATH}"
end

desc "load files sent"
task :load_old_messages do
  sh "#{RUBY_BIN} #{RUN_FILE} #{SERIALIZED_FILE} #{THREADS} #{OLD_MESSAGES_PATH}"
end

desc "load files sent"
task :test_load do
  1.upto( 5 ) do |i|
    if File.exist?( SERIALIZED_FILE )
      FileUtils.rm( SERIALIZED_FILE )
    end
    sh "#{RUBY_BIN} #{RUN_FILE} #{SERIALIZED_FILE} #{i} #{OLD_MESSAGES_PATH}"
  end
end

desc "run utility"
task :run do
  sh "#{RUBY_BIN} #{RUN_FILE} #{SERIALIZED_FILE}"
end

desc "run skynet server"
task :start_skynet do
  puts ARGV[1]
  sh "skynet start --workers=6 -r #{ARGV[1]}"
  sh "skynet console -r #{ARGV[1]}"
end

desc "stop skynet server"
task :stop_skynet do
  sh "skynet stop"
end
