RUBY_BIN = "jruby"
PATH = "/home/hone/.evolution/mail/imap/hone@mail.hone.wornpath.net/folders/INBOX"
SERIALIZED_FILE = "mail.dump"
RUN_FILE = "runner.rb"

desc "load files"
task :load do
  sh "#{RUBY_BIN} #{RUN_FILE} #{SERIALIZED_FILE} #{PATH}"
end

desc "run utility"
task :run do
  sh "#{RUBY_BIN} #{RUN_FILE} #{SERIALIZED_FILE}"
end

desc "run skynet server"
task :start_skynet_server_from_address_count do
  sh "skynet start --workers -r from_address_count.rb"
end

desc "run skynet console"
task :skynet_console do
  sh "skynet console -r *.rb"
end
