require 'rake/clean'

CLEAN.include( '*.gch', '*.o' )
CLOBBER.include( 'convolutions' )

OPENCV_UTILS = '../../opencv_utils'

CC = 'gcc'
CFLAGS = `pkg-config --cflags opencv`.chomp + "-I#{OPENCV_UTILS}"
LFLAGS = `pkg-config --libs opencv`.chomp

OBJECTS = ['convolutions.o', 'image_raii.o', 'matrix_raii.o']

task :default => ["convolutions"]

file "convolutions" => OBJECTS do
  sh "#{CC} -o convolutions #{OBJECTS.join( ' ' )} #{LFLAGS}"
end

file "convolutions.o" => ['convolutions.cpp', "#{OPENCV_UTILS}/image_raii.cpp"] do
  sh "#{CC} -c convolutions.cpp #{CFLAGS}"
end

file "image_raii.o" => ["#{OPENCV_UTILS}/image_raii.cpp", "#{OPENCV_UTILS}/image_raii.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/image_raii.cpp #{CFLAGS}"
end

file "matrix_raii.o" => ["#{OPENCV_UTILS}/matrix_raii.cpp", "#{OPENCV_UTILS}/matrix_raii.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/matrix_raii.cpp #{CFLAGS}"
end
