require 'rake/clean'

CLEAN.include( '*.gch', '*.o' )
CLOBBER.include( 'convolutions' )

CC = 'gcc'
CFLAGS = `pkg-config --cflags opencv`
LFLAGS = `pkg-config --libs opencv`

OBJECTS = ['convolutions.o', 'image_raii.o', 'matrix_raii.o']

task :default => ["convolutions"]

file "convolutions" => OBJECTS do
  sh "#{CC} -o convolutions #{OBJECTS.join( ' ' )} #{LFLAGS}"
end

file "convolutions.o" => ['convolutions.cpp'] do
  sh "#{CC} -c convolutions.cpp #{CFLAGS}"
end

file "image_raii.o" => ['image_raii.cpp', 'image_raii.h'] do
  sh "#{CC} -c image_raii.cpp #{CFLAGS}"
end

file "matrix_raii.o" => ['matrix_raii.cpp', 'matrix_raii.h'] do
  sh "#{CC} -c matrix_raii.cpp #{CFLAGS}"
end
