require 'rake/clean' 
NAME = 'face_detect'

CLEAN.include( '*.gch', '*.o' )
CLOBBER.include( NAME )

# Paths
OPENCV_UTILS = "../opencv_utils"
HAGER_DIR = "data/ForVision"
HAGER_PICS = (1..13).collect {|i| "#{HAGER_DIR}/Hager#{i}.jpg" }
RAF_DIR = "data/picMe"
RAF_PICS = (1..10).collect {|i| "#{RAF_DIR}/raphael_#{i}.png" }
LAUREN_DIR = "data/lauren"
LAUREN_PICS = (1..8).collect {|i| "#{LAUREN_DIR}/lauren#{i}.jpg" }
SUPERBAD_DIR = "data/superbad"
OUTPUT_DIR_NAME = "face_detect"

CC = 'gcc'
CFLAGS = "#{`pkg-config --cflags opencv`.chomp} -I#{OPENCV_UTILS} -I."
LFLAGS = `pkg-config --libs opencv`.chomp

OBJECTS = ['test.o', "#{NAME}.o", "image_raii.o", "string_util.o", "window_raii.o"]

task :default => ['test']

task :run do
  sh "./test #{SUPERBAD_DIR}/mclovin2.jpg"
end

file 'test' => OBJECTS do
  sh "#{CC} -o test #{OBJECTS.join( ' ' )} #{LFLAGS}"
end

file 'test.o' => ['test.cpp'] do
  sh "#{CC} -c test.cpp #{CFLAGS}"
end

file "#{NAME}.o" => ["#{NAME}.cpp", "#{NAME}.hpp"] do
  sh "#{CC} -c #{NAME}.cpp #{CFLAGS}"
end

file "image_raii.o" => ["#{OPENCV_UTILS}/image_raii.cpp", "#{OPENCV_UTILS}/image_raii.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/image_raii.cpp #{CFLAGS}"
end

file "window_raii.o" => ["#{OPENCV_UTILS}/window_raii.cpp", "#{OPENCV_UTILS}/window_raii.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/window_raii.cpp #{CFLAGS}"
end

file "string_util.o" => ["#{OPENCV_UTILS}/string_util.cpp", "#{OPENCV_UTILS}/string_util.hpp"] do
  sh "#{CC} -c #{OPENCV_UTILS}/string_util.cpp #{CFLAGS}"
end
